name: C:\Anaconda3\envs\theano_dbn
dependencies:
- libpython=1.0=py27_1
- mingw=4.7=1
- msvc_runtime=1.0.1=vc9_0
- numpy=1.10.1=py27_0
- pip=7.1.2=py27_0
- python=2.7.10=5
- scipy=0.16.0=np110py27_0
- setuptools=18.5=py27_0
- wheel=0.26.0=py27_1
- pip:
  - django==1.9
  - image==1.4.3
  - pillow==3.0.0
  - six==1.10.0
  - theano==0.7.0
  - utils==0.8.0

